// <auto-generated />
namespace ARMArchiveApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixUpdateDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixUpdateDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201906211732107_FixUpdateDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
